[package]
name = "homebase_starknet"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.8.2"

[dependencies.openzeppelin]
git = "https://github.com/OpenZeppelin/cairo-contracts.git"
rev = "d916297c00f9c901d4e4c248c55e6b9ae3aaec37"

[[target.starknet-contract]]
name = "token"
path = "contracts/token.cairo"
sierra = true
casm = true

[[target.starknet-contract]]
name = "escrow"
path = "contracts/escrow.cairo"
sierra = true
casm = true

[[target.starknet-contract]]
name = "loan"
path = "contracts/loan.cairo"
sierra = true
casm = true

[[target.starknet-contract]]
name = "paymaster"
path = "contracts/paymaster.cairo"
sierra = true
casm = true

[[target.starknet-contract]]
name = "swap"
path = "contracts/swap.cairo"
sierra = true
casm = true

[[target.starknet-contract]]
name = "credit_card_sim"
path = "contracts/credit_card_sim.cairo"
sierra = true
casm = true
